#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calendar.Droid.Resource", IsApplication=true)]

namespace Calendar.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Calendar.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Calendar.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Alarm = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AzanMaghreb = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AzanSobh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AzanZohr = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BigLogo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Calendar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Camera = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Clock = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Delete = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Edit = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Favorite = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Finance = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Ghorob = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int HealthCare = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Home = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Learn = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MainGoal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Menu = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Next = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int NimeShab = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Note = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Pay = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Plan = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Planing = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Plus = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Prev = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Progress = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Recive = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Relation = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Search = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Setting = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Shortcut = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Splash = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int splash_background = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int SubGoal = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ToleAftab = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int UnderDev = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
